layerrule {
  name = ignis_main
  blur = on
  ignore_alpha = 0
  xray = 0
  blur_popups = on
  match:namespace = ^(ignis_CORNER.*|ignis_BAR.*|ignis_NOTIFICATION_POPUP.*|ignis_CONTROL_CENTER.*|ignis_POWERMENU.*|ignis_OSD_BL|ignis_OSD_VOL|ignis_CALENDAR.*)$
}


layerrule {
  name = anim_rules
  no_anim = on
  match:namespace = ^(corner.*|ignis_BAR.*|ignis_NOTIFICATION_POPUP.*|ignis_CONTROL_CENTER.*|ignis_POWERMENU.*|ignis_OSD_BL|ignis_OSD_VOL|ignis_CALENDAR)$
}

layerrule {
  name = anim_sidebar
  animation = slide right
  blur_popups =  off
  match:namespace = ^(ignis_CONTROL_CENTER.*|ignis_OSD_BL|ignis_OSD_VOL.*)$
}

layerrule {
  name = anim_media
  animation = none
  match:namespace = ^(ignis_MEDIA)$
}


