exec-once = ignis init
bind = SUPER ALT, B, exec, ignis reload
bind = Super, Space ,exec , vicinae vicinae://toggle
bind = SUPER, V, exec, vicinae vicinae://extensions/vicinae/clipboard/history
bind = SUPER, Period, exec,vicinae vicinae://extensions/vicinae/vicinae/search-emojis
bind = SUPER, ESCAPE, exec, ignis toggle-window ignis_POWERMENU
bind = SUPER, I, exec, ignis toggle-window ignis_SETTINGS
