from ignis import widgets
from modules.shared_widgets.corner import Corner


class CornerAll(widgets.Window):
    def __init__(self, monitor_id: int = 0):
        super().__init__(
            namespace=f"ignis_CORNER_{monitor_id}",
            exclusivity="exclusive",
            css_classes=["rec-unset"],
            anchor=["top", "right", "bottom", "left"],
            layer="bottom",
            child=widgets.CenterBox(
                vertical=True,
                start_widget=widgets.Box(
                    child=[
                        widgets.CenterBox(
                            vertical=False,
                            vexpand=True,
                            hexpand=True,
                            start_widget=widgets.Box(
                                child=[
                                    Corner(
                                        orientation="top-left",
                                        css_classes=["corner-top"],
                                        halign="end",
                                        valign="start",
                                        width_request=30,
                                        height_request=30,
                                    )
                                ]
                            ),
                            end_widget=widgets.Box(
                                child=[
                                    Corner(
                                        orientation="top-right",
                                        halign="end",
                                        valign="start",
                                        css_classes=["corner-top"],
                                        width_request=30,
                                        height_request=30,
                                    ),
                                ],
                            ),
                        ),
                    ]
                ),
                end_widget=widgets.Box(
                    child=[
                        widgets.CenterBox(
                            vertical=False,
                            vexpand=True,
                            hexpand=True,
                            start_widget=widgets.Box(
                                child=[
                                    Corner(
                                        orientation="bottom-left",
                                        css_classes=["corner"],
                                        halign="end",
                                        valign="end",
                                        width_request=30,
                                        height_request=30,
                                    )
                                ]
                            ),
                            end_widget=widgets.Box(
                                child=[
                                    Corner(
                                        orientation="bottom-right",
                                        halign="end",
                                        valign="end",
                                        css_classes=["corner"],
                                        width_request=30,
                                        height_request=30,
                                    ),
                                ],
                            ),
                        ),
                    ]
                ),
            ),
        )
